# Generated by Django 2.2.5 on 2020-12-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_villain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swapindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.IntegerField()),
                ('courseName', models.CharField(max_length=60)),
                ('currentIndex', models.IntegerField()),
                ('wantIndex', models.IntegerField()),
                ('username', models.CharField(max_length=60)),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Villain',
        ),
    ]
