# Generated by Django 2.2.5 on 2020-12-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20201211_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swapindex',
            old_name='userId',
            new_name='chatId',
        ),
        migrations.RemoveField(
            model_name='swapindex',
            name='courseName',
        ),
    ]
