# Generated by Django 2.2.5 on 2020-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201212_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapindex',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
