# Generated by Django 2.2.5 on 2020-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_swapindex_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swapindex',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
