# Generated by Django 3.2.2 on 2021-05-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swapindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=60)),
                ('currentIndex', models.IntegerField()),
                ('wantIndex', models.IntegerField()),
                ('username', models.CharField(max_length=60)),
                ('chatId', models.IntegerField()),
            ],
        ),
    ]
