# Generated by Django 3.2.2 on 2021-05-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapindex',
            name='id',
        ),
        migrations.AddField(
            model_name='swapindex',
            name='entryId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
